

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository

image: openjdk:8-jdk-alpine

services:
  - docker:dind
  
build:
  stage: test
  script:
    - './mvnw package'
  only:
    - master

