spring:
  application:
    name: Transport Booking
  output:
    ansi:
      enabled: always
  datasource:
    schema: classpath:sql/schema.sql
    url: jdbc:postgresql://localhost:15432/postgres
    username: bob
    password: marley
    platform: POSTGRESQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        encoder: ch.octo.blog.transport.utils.JacksonEncoderWithOptionalSupport
        decoder: ch.octo.blog.transport.utils.JacksonDecoderWithOptionalSupport
        contract: org.springframework.cloud.openfeign.support.SpringMvcContract

ribbon:
  eureka:
    enabled: false

connections:
  ribbon:
    NIWSServerListClassName : com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8080

server:
  port: 8081

logging:
  level:
    root: WARN
    ch.octo.blog.transport: DEBUG
debug: false
