spring:
  application:
    name: Transport Booking
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    platform: POSTGRESQL
    initialization-mode: always
    schema: classpath:sql/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  cloud:
    refresh:
      enabled: false # https://github.com/spring-cloud/spring-cloud-commons/issues/355

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        encoder: ch.octo.blog.transport.utils.JacksonEncoderWithOptionalSupport
        decoder: ch.octo.blog.transport.utils.JacksonDecoderWithOptionalSupport
        contract: org.springframework.cloud.openfeign.support.SpringMvcContract

ribbon:
  eureka:
    enabled: false

connections:
  ribbon:
    listOfServers: ${CONNECTION_LOOKUP_SERVER}
    NIWSServerListClassName : com.netflix.loadbalancer.ConfigurationBasedServerList

server:
  port: 8081

logging:
  level:
    root: WARN
    ch.octo.blog.transport: DEBUG
debug: false

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: bob
    password: marley

connections:
  ribbon:
    listOfServers: localhost:8080